### ISSUE TITLE
Сверстать страницу входа и регистрации

### ISSUE THREAD

**Issue by Postlog** [bmstu-iu9/ptp2021-4-chat#19]
_Создать вёрстку для единой страницы входа и регистрации_

Требования:
- Верстка должна быть адаптивной
- При регистрации должно присутствовать поле повтора пароля (оно должно появляться при нажатии на кнопку регистрации) и должна быть валидация сложности пароля: минимум 6 символов, наличие букв и цифр
- При логине не должно быть поля с повтором пароля
- Реализовать появление красного текста внутри формы с сообщением об ошибке при логине или регистрации. Например, "Пароль недостаточно сложный" или "Пользователь с заданным логином и паролем не найден"

**Comment by boomb0om** [comment]
По поводу адаптивности: нужно еще сделать так, чтобы на мобильных устройствах окошко с информацией было под окошком с логином, а не над ним

**Comment by Postlog** [comment]
Эта заявка зависит от заявок #41 #42 #43 #44

**Comment by Mazdaywik** [comment]
Если написать номера заявок внутри списка, они раскроются:
```Markdown
* #41
* #42
* #43
* #44
```

Список будет выглядеть так:
* #41
* #42
* #43
* #44

**Comment by Postlog** [comment]
Заявка не имеет смысла, т.к. существует Milestone
