### ISSUE TITLE
Не повторяйте эту ошибку

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/ptp2021-4-chat#71]
https://t.me/ilyabirman_channel/6078

![image](https://user-images.githubusercontent.com/1309859/126905414-78d3b367-8195-4eef-ae74-7ce3b2ed444d.png)

**Comment by Postlog** [comment]
Не очень понятно, в чем суть ошибки. Если пользователь пытается зарегестрироваться, указывая уже существующее имя почты, то логично, что ему выдаст такую ошибку

**Comment by Postlog** [comment]
Или имеется ввиду, что нужно давать ссылку на авторизацию с этим логином?

**Comment by Mazdaywik** [comment]
Не логично. Я зарегистрировался, год назад. Забыл об этом. Захожу снова, регистрируюсь. Если я введу тот же адрес и пароль, то логично не выдавать ошибку, а сразу зайти в зарегистрированный ранее аккаунт. Это было бы идеальное поведение для таких условий.

Либо поменять текст сообщения об ошибке. Вместо «Данный email ранее регистрировался», написать, «Вы уже ранее регистрировались, перейти на <u>страницу логина</u>?».



> Или имеется ввиду, что нужно давать ссылку на авторизацию с этим логином?

Да, это имеется ввиду. Пока писал комментарий, написали Вы.

**Comment by Pug-coder** [comment]
А если пользователь ввел уже зарегистрированный email, но неверный пароль, что в таком случае выводить?

**Comment by Mazdaywik** [comment]
Если пользователь ввёл два разных пароля в поля «Пароль» и «Подтверждение пароля», то выдаётся ошибка, что пароли не совпадают, независимо от существования email’а.

Если пользователь ввёл верные email и пароль, то логиним его в его старый аккаунт. В некотором смысле операция регистрации [идемпотентна](https://ru.wikipedia.org/wiki/%D0%98%D0%B4%D0%B5%D0%BC%D0%BF%D0%BE%D1%82%D0%B5%D0%BD%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C).

Если пользователь ввёл известный email и не тот пароль, то выдаём сообщение об ошибке с предложением перейти в окно логина: _Вы уже ранее регистрировались, перейти на <a href='#'>страницу логина</a>?_ Если перейти по ссылке, то на странице логина в поле email будет введён правильный логин.

**Comment by Postlog** [comment]
Спасибо за рекомендации, мы постараемся именно так и сделать :)
