### ISSUE TITLE
Вынести функции валидации в отдельный общий файл

### ISSUE THREAD

**Issue by Postlog** [bmstu-iu9/ptp2021-4-chat#80]
Так как валидировать имя пользователя и пароль нужно как на фронтенде, так и на бекенде, то лучшим решением в нашем случае является вынести функции валидации в папку `common/` (которая будет лежать рядом с папками `src/` и `server/`) в файл `common.js`

Таким образом, мы сможем обращаться к одинм и тем же функциям для валидации как с фронтенда, так и с бекенда. Однако всё это требует некоторой подготовки: 
* Во-первых, в файле `common/common.js` нужно объявить функцию, которая возвращает `true`, если скрипт исполняется в окружении NodeJS и `false` в противном случае (если выполняется, например, в браузере). В интернете есть куча примеров как такую функцию написать. Т.к. в NodeJS используется система модулей, то нам нужно экспортировать через `module.exports` все функции, что мы объявим в файле, **но** делать это надо только в случае, если код выполняется в NodeJS:
```javascript
if (isNode()) {
  module.exports = {
    // ...
    // функции, которые нужно экспортировать
    // ...
  }
}
```
* Во-вторых, в конфиге сервера (`server/config.js`) нужно добавить ключ `commonPath` с путём до папки `common` (по аналогии с ключом `publicPath`)
* И последнее - нужно добавить middleware для просмотра статики в папке common (в файле `server/middleware/index.js` для `staticRouter` нужно добавить новый обработчик `express.static`, обслуживающий путь `/common` и просматривающий папку `common/`):
```javascript
staticRouter.use('/common', express.static(commonPath))
```

Прежде чем приступить к данной заявке, должны быть закрыты следующие:
* #77 
* #79

**Comment by VladBermishev** [comment]
#86
