### ISSUE TITLE
Вынести объекты ошибок в отдельный файл

### ISSUE THREAD

**Issue by Postlog** [bmstu-iu9/ptp2021-4-chat#87]
HTTP-ошибки генерируются вызывом `createError(...)` ([тык](https://github.com/bmstu-iu9/ptp2021-4-chat/blob/889965552789dea58df0af77e0d0e633deb9b8ff/server/services/authentication.js#L20), [тык](https://github.com/bmstu-iu9/ptp2021-4-chat/blob/889965552789dea58df0af77e0d0e633deb9b8ff/server/services/registration.js#L24)). При этом код ошибки и сообщение объявляются там же, где и вызывается функция. 

Нужно вынести в файл `common/common.js` все ошибки, а при вызове `createError`  обращаться к нужной

```javascript
...
...
...

const errors = {
  usernameNotRegistered: {
    code: 401,
    message: 'username-not-registered'
  },
  incorrectPassword: {
    code: 401,
    message: 'incorrect-password'
  },
  usernameAlreadyRegistered: {
    code: 409,
    message: 'username-already-registered'
  },
  incorrectBody: {
    code: 400,
    message: 'incorrect-body'
  }
}


if (isNode()) {
  module.exports = {
    ...
    errors
  }
}
 ```

Далее нужно изменить все вызовы `createError` (чтобы удобно раскидывать значения объектов по аргументам при вызове, можно использовать spread-оператор: `createError(...Objects.values(errors.incorrectBody))`). При этом вызов ошибок нужно изменить следующим образом:
* [Здесь](https://github.com/bmstu-iu9/ptp2021-4-chat/blob/889965552789dea58df0af77e0d0e633deb9b8ff/server/services/authentication.js#L20) передавать `usernameNotRegistered`
* [Здесь](https://github.com/bmstu-iu9/ptp2021-4-chat/blob/889965552789dea58df0af77e0d0e633deb9b8ff/server/services/authentication.js#L26) передавать `incorrectPassword`
* [Здесь](https://github.com/bmstu-iu9/ptp2021-4-chat/blob/889965552789dea58df0af77e0d0e633deb9b8ff/server/services/registration.js#L24) передавать `usernameAlreadyRegistered`
* [Здесь](https://github.com/bmstu-iu9/ptp2021-4-chat/blob/889965552789dea58df0af77e0d0e633deb9b8ff/server/middleware/usernameAndPassword.js#L8) и [здесь](https://github.com/bmstu-iu9/ptp2021-4-chat/blob/889965552789dea58df0af77e0d0e633deb9b8ff/server/middleware/usernameAndPassword.js#L19) передавать `incorrectBody` (там вообще функция createError не используется, что нужно само собой исправить)

**Comment by VladBermishev** [comment]
#89
