### ISSUE TITLE
Написать обёртку для WS-клиента

### ISSUE THREAD

**Issue by Postlog** [bmstu-iu9/ptp2021-4-chat#98]
Написать обертку над стандартным WebSocket клиентом для фронтенда

Обёртка должна позволять добавлять обработчики на ответ на сообщение, который придет от сервера. Для этого в каждом запросе нужно добавлять поле ID. Сервер, получив такое сообщение, обработает его и отправит ответ, добавив к нему тот же самый ID. Таким образом можно отслеживать, на какой запрос ответил сервер. Лучше всего это реализовать при помощи промисов: при каждом запросе на сервер к ID запроса будут привязываться функции `reject` и `resolve`. При получении сообщения от сервера будет считываться занчение ID и осуществляться получение привязанных функций `reject` и `resolve`. В случае, если сервер ответил ошибкой, будет вызываться `reject`, в противном случае - `resolve`. Это позволит строить следующие удобные конструкции:
```javascript
webSocketClient.send('hello, world!')
        .then(answer => ...)
        .catch(error => ...)
```

**Важно!**: помимо этого, у обертки должна присутсвовать возможности просто подписываться на сообщения от сервера (так же, как и в стандартном классе WebSocket)

**Comment by boomb0om** [comment]
Я правильно понял, что json в сообщениях выглядит так?
```
{
  "ID": integer, 
  "payload": {...}
}
```

**Comment by Postlog** [comment]
Почти. На сервере настроено, чтобы JSON выглядел так
'''
{
  "$id": integer - абсолютно любое число
  "payload": {}
}
'''

Мы решили обозначить ID именно таким образом, чтобы как-то указать, что это служебное поле, а не часть полезной нагрузки

**Comment by Postlog** [comment]
Забыл уточнить, что сервер ответил ошибкой если в объекте `payload` есть объект `error`:
```json
{
  "$id": 123,
  "payload": {
    "error": {
       "code": 228,
       "message": "я сломался :("
    }
  }
}
```

При этом если ошибка вызвана клиентом (неправильно составлен запрос, не передан $id или в запросе переданы некорректные данные), то сервер _разрывает_ соединение
